# Generated by Django 2.1.5 on 2019-01-24 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='fromUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_message1', to='Flea.UserInfo'),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='toUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_message2', to='Flea.UserInfo'),
        ),
    ]
